mybatis:
  config-location: classpath:mybatis-config.xml
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    url: jdbc:mysql://localhost:3306/forum?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
  velocity:
    suffix: .html
    toolbox-config-location: toolbox.xml
server:
  port: 3557
